In [1]:
import numpy as np
arr = np.random.randint(0, 11, (3, 3))
print("Array:\n", arr)
print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Standard Deviation:", np.std(arr))

Array:
 [[3 9 7]
 [8 1 1]
 [0 9 2]]
Sum: 40
Mean: 4.444444444444445
Standard Deviation: 3.5311663515712675


In [2]:
arr = np.arange(10)
print("Array:", arr)
print("Cumulative Sum:", np.cumsum(arr))

Array: [0 1 2 3 4 5 6 7 8 9]
Cumulative Sum: [ 0  1  3  6 10 15 21 28 36 45]


In [3]:
a = np.random.randint(1, 10, (2, 3))
b = np.random.randint(1, 10, (2, 3))
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)

Addition:
 [[11  9 16]
 [ 7 10 12]]
Subtraction:
 [[-5 -5  2]
 [ 5  4  4]]
Multiplication:
 [[24 14 63]
 [ 6 21 32]]
Division:
 [[0.375      0.28571429 1.28571429]
 [6.         2.33333333 2.        ]]


In [4]:
print("Identity Matrix:\n", np.eye(4))

Identity Matrix:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [5]:
a = np.array([5, 10, 15, 20, 25])
print("Result:", a / 5)

Result: [1. 2. 3. 4. 5.]


In [6]:
arr = np.arange(12)
print("Reshaped:\n", arr.reshape(3, 4))

Reshaped:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
matrix = np.random.randint(0, 10, (3, 3))
print("Flattened:", matrix.flatten())

Flattened: [2 8 5 2 2 5 7 3 2]


In [8]:
a = np.random.randint(0, 10, (3, 3))
b = np.random.randint(0, 10, (3, 3))
print("Horizontal:\n", np.hstack((a, b)))
print("Vertical:\n", np.vstack((a, b)))

Horizontal:
 [[7 9 6 8 4 4]
 [1 3 5 6 9 8]
 [4 3 8 2 3 7]]
Vertical:
 [[7 9 6]
 [1 3 5]
 [4 3 8]
 [8 4 4]
 [6 9 8]
 [2 3 7]]


In [9]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6, 7])
a_padded = np.pad(a, (0, 1), 'constant')
print("Concatenated:\n", np.concatenate((a_padded, b)).reshape(2, -1))

Concatenated:
 [[1 2 3 0]
 [4 5 6 7]]


In [10]:
matrix = np.random.randint(0, 10, (3, 2))
print("Result:\n", matrix.T.reshape(3, 2))

Result:
 [[0 4]
 [0 9]
 [4 0]]


In [11]:
arr = np.arange(15)
print("Elements:", arr[2:11:2])

Elements: [ 2  4  6  8 10]


In [12]:
matrix = np.random.randint(0, 10, (5, 5))
print("Submatrix:\n", matrix[1:4, 2:5])

Submatrix:
 [[9 4 6]
 [7 6 5]
 [4 2 6]]


In [13]:
arr = np.array([5, 11, 8, 15, 3, 12])
arr[arr > 10] = 10
print("Result:", arr)

Result: [ 5 10  8 10  3 10]


In [14]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print("Selected:", arr[[0, 2, 4, 6]])

Selected: [10 30 50 70]


In [15]:
arr = np.arange(10)
print("Reversed:", arr[::-1])

Reversed: [9 8 7 6 5 4 3 2 1 0]


In [16]:
matrix = np.random.randint(0, 10, (3, 3))
row = np.array([1, 2, 3])
print("Result:\n", matrix + row)

Result:
 [[ 3 10 12]
 [ 2  5  6]
 [ 1 11  4]]


In [17]:
arr = np.array([1, 2, 3, 4, 5])
print("Result:", arr * 3)

Result: [ 3  6  9 12 15]


In [18]:
matrix = np.random.randint(0, 10, (3, 3))
col = np.array([[1], [2], [3]])
print("Result:\n", matrix - col)

Result:
 [[ 8 -1  2]
 [ 0  0  7]
 [-2  0 -3]]


In [19]:
arr = np.random.randint(0, 5, (2, 3, 4))
print("Result:\n", arr + 10)

Result:
 [[[14 14 11 10]
  [12 11 11 13]
  [10 10 12 11]]

 [[14 10 12 11]
  [12 12 13 11]
  [14 13 11 13]]]


In [20]:
a = np.array([[1], [2], [3], [4]])
b = np.array([[10, 20, 30, 40, 50]])
print("Result:\n", a + b)

Result:
 [[11 21 31 41 51]
 [12 22 32 42 52]
 [13 23 33 43 53]
 [14 24 34 44 54]]


In [21]:
arr = np.random.randint(1, 10, (2, 3))
print("Square Roots:\n", np.sqrt(arr))

Square Roots:
 [[1.         3.         1.41421356]
 [2.64575131 1.         1.73205081]]


In [22]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 4, 3, 2, 1])
print("Dot Product:", np.dot(a, b))

Dot Product: 35


In [23]:
a = np.array([5, 10, 15, 20])
b = np.array([3, 12, 13, 25])
print("Comparison:", a > b)

Comparison: [ True False  True False]


In [24]:
arr = np.random.randint(0, 10, (2, 3))
print("Doubled:\n", arr * 2)

Doubled:
 [[ 2  0 18]
 [14  0 18]]


In [25]:
arr = np.random.randint(0, 100, 100)
print("Sum of Evens:", np.sum(arr[arr % 2 == 0]))

Sum of Evens: 2528


In [26]:
matrix = np.random.randint(0, 10, (3, 3))
print("Determinant:", np.linalg.det(matrix))

Determinant: -42.00000000000002


In [27]:
matrix = np.array([[4, 7], [2, 6]])
inv = np.linalg.inv(matrix)
print("Inverse:\n", inv)
print("Verification:\n", np.dot(matrix, inv))

Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Verification:
 [[1. 0.]
 [0. 1.]]


In [28]:
matrix = np.array([[4, 2], [1, 3]])
eigvals, eigvecs = np.linalg.eig(matrix)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [29]:
A = np.array([[2, 3], [4, 6]])
b = np.array([5, 10])
try:
    print("Solution:", np.linalg.solve(A, b))
except:
    print("System is singular")

Solution: [nan nan]


In [30]:
matrix = np.random.randint(0, 10, (3, 3))
U, S, Vt = np.linalg.svd(matrix)
print("U:\n", U)
print("S:", S)
print("Vt:\n", Vt)
reconstructed = U @ np.diag(S) @ Vt
print("Reconstructed:\n", reconstructed)

U:
 [[-4.84150062e-01  8.74984982e-01  3.72243643e-18]
 [-6.18707814e-01 -3.42345792e-01 -7.07106781e-01]
 [-6.18707814e-01 -3.42345792e-01  7.07106781e-01]]
S: [1.60215123e+01 2.51219877e+00 1.65637964e-16]
Vt:
 [[-8.76424193e-01 -3.82797645e-01 -2.92141398e-01]
 [-3.63153732e-01  9.23832216e-01 -1.21051244e-01]
 [-3.16227766e-01  3.33066907e-16  9.48683298e-01]]
Reconstructed:
 [[6. 5. 2.]
 [9. 3. 3.]
 [9. 3. 3.]]
